export const announcements = [
  {
    id: 1,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Треба вирішити земельне питання',
    comment:
      'Є два спадкоємця, обидва бажають володіти ділянкою , домовитись не виходить, потрібна допомога досвідченого юриста',
    author: 'Іван Мазепа',
    price: 4875,
    tel: '+565291-4561-51',
  },
  {
    id: 2,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Юридична консультація по спадщині',
    comment: 'Необхідна допомога в складанні заповіту та оформленні спадщини',
    author: 'Марія Петренко',
    price: 3000,
    tel: '+565291-1234-56',
  },
  {
    id: 3,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Допомога у вирішенні податкових спорів',
    comment: 'Шукаю досвідченого юриста для оскарження податкових рішень',
    author: 'Олег Ковальчук',
    price: 4500,
    tel: '+565291-7890-12',
  },
  {
    id: 4,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Консультація по розлученню',
    comment: 'Потрібна консультація щодо процесу розлучення та розділу майна',
    author: 'Анна Мельник',
    price: 4000,
    tel: '+565291-3456-78',
  },
  {
    id: 5,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Питання по оренді нерухомості',
    comment:
      'Шукаю допомогу у складанні договору оренди та врегулюванні спорів',
    author: 'Ірина Коваленко',
    price: 3500,
    tel: '+565291-9876-54',
  },
  {
    id: 6,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Консультація по захисту прав споживачів',
    comment: 'Необхідно оскаржити рішення продавця щодо повернення товару',
    author: 'Володимир Соколов',
    price: 2000,
    tel: '+565291-6543-21',
  },
  {
    id: 7,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Допомога у трудових спорах',
    comment: 'Шукаю юриста для вирішення конфлікту з роботодавцем',
    author: 'Катерина Бондаренко',
    price: 3800,
    tel: '+565291-4567-89',
  },
  {
    id: 8,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Юридична консультація щодо фінансів',
    comment: 'Потрібна допомога у врегулюванні боргових зобов`язань',
    author: 'Михайло Поліщук',
    price: 4200,
    tel: '+565291-3210-98',
  },
  {
    id: 9,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Питання з корпоративного права',
    comment: 'Шукаю юриста для супроводу корпоративних угод',
    author: 'Олена Гончар',
    price: 5000,
    tel: '+565291-8765-43',
  },
  {
    id: 10,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Консультація з міжнародного права',
    comment: 'Необхідна консультація щодо ведення бізнесу за кордоном',
    author: 'Сергій Вовк',
    price: 5500,
    tel: '+565291-1122-33',
  },
  {
    id: 11,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Юридична допомога у кримінальних справах',
    comment: 'Потрібен адвокат для захисту у кримінальній справі',
    author: 'Олександр Петров',
    price: 6000,
    tel: '+565291-5566-77',
  },
  {
    id: 12,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Консультація з медичного права',
    comment: 'Шукаю допомогу юриста з медичних питань',
    author: 'Ірина Хоменко',
    price: 4800,
    tel: '+565291-9988-77',
  },
  {
    id: 13,
    announcementDate: new Date().toLocaleDateString('en-us', {
      weekday: 'long',
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    }),
    type: 'client',
    title: 'Допомога у вирішенні земельних питань',
    comment: 'Потрібна консультація юриста з земельних справ',
    author: 'Тарас Козак',
    price: 4400,
    tel: '+565291-2233-44',
  },
];
